image: python:latest

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - python setup.py test
    - pip install tox flake8  # you can also use tox
    - tox -e py36,flake8

run:
  script:
    - python -m pip install -r cli/requirements.txt --user
    - python cli/main.py
  artifacts:
    paths:
      - dist/*.whl
