# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/sdmay23-47/petalinux/hw/hw/hw.srcs/sources_1/bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0.xci
# IP: The module: 'system_auto_rs_w_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/sdmay23-47/petalinux/hw/hw/hw.srcs/sources_1/bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_rs_w_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: u:/sdmay23-47/petalinux/hw/hw/hw.srcs/sources_1/bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_rs_w_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: u:/sdmay23-47/petalinux/hw/hw/hw.srcs/sources_1/bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0.xci
# IP: The module: 'system_auto_rs_w_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/sdmay23-47/petalinux/hw/hw/hw.srcs/sources_1/bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_rs_w_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: u:/sdmay23-47/petalinux/hw/hw/hw.srcs/sources_1/bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_rs_w_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
