# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: U:/sdmay23-47/petalinux/hw/CyDAQ_proto_1/CyDAQ_proto_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
# IP: The module: 'design_1_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/sdmay23-47/petalinux/hw/CyDAQ_proto_1/CyDAQ_proto_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: U:/sdmay23-47/petalinux/hw/CyDAQ_proto_1/CyDAQ_proto_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
# IP: The module: 'design_1_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/sdmay23-47/petalinux/hw/CyDAQ_proto_1/CyDAQ_proto_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
