# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner/BasicOperation.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_basic_operation(object):
    def setupUi(self, basic_operation):
        basic_operation.setObjectName("basic_operation")
        basic_operation.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(basic_operation.sizePolicy().hasHeightForWidth())
        basic_operation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setUnderline(False)
        basic_operation.setFont(font)
        basic_operation.setStyleSheet("background-color: #d9d9d9;")
        self.centralwidget = QtWidgets.QWidget(basic_operation)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 16px;\n"
"    color: #033f63;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #033f63;\n"
"    color: #d9d9d9;\n"
"    border-radius: 4px;\n"
"    padding: 8px 21px;\n"
"}\n"
"\n"
"#dac_btn, #sampling_rate_btn, #input_btn, #filter_btn, #corners_btn {\n"
"    margin: 0 4px;\n"
"}\n"
"\n"
"#dac_btn {\n"
"    border: 2px solid #033f63;\n"
"}\n"
"\n"
"#sampling_rate_btn, #input_btn, #filter_btn, #corners_btn, #previous_btn {\n"
"    background-color: none;\n"
"    border: 2px solid #033f63;\n"
"    color: #033f63;\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BasicOperationLabel = QtWidgets.QLabel(self.centralwidget)
        self.BasicOperationLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.BasicOperationLabel.setObjectName("BasicOperationLabel")
        self.verticalLayout_2.addWidget(self.BasicOperationLabel)
        self.ConfigLayout = QtWidgets.QGridLayout()
        self.ConfigLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ConfigLayout.setObjectName("ConfigLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ConfigLayout.addWidget(self.line, 2, 0, 1, 2)
        self.InputLayout_2 = QtWidgets.QGridLayout()
        self.InputLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.InputLayout_2.setObjectName("InputLayout_2")
        self.input_list = QtWidgets.QListWidget(self.centralwidget)
        self.input_list.setMaximumSize(QtCore.QSize(16777215, 300))
        self.input_list.setTabKeyNavigation(True)
        self.input_list.setModelColumn(0)
        self.input_list.setUniformItemSizes(False)
        self.input_list.setObjectName("input_list")
        item = QtWidgets.QListWidgetItem()
        self.input_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.input_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.input_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.input_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.input_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.input_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.input_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.input_list.addItem(item)
        self.InputLayout_2.addWidget(self.input_list, 0, 0, 1, 1)
        self.ConfigLayout.addLayout(self.InputLayout_2, 1, 1, 1, 1)
        self.SampleRateLayout = QtWidgets.QGridLayout()
        self.SampleRateLayout.setObjectName("SampleRateLayout")
        self.sample_rate_presets = QtWidgets.QListWidget(self.centralwidget)
        self.sample_rate_presets.setMinimumSize(QtCore.QSize(0, 300))
        self.sample_rate_presets.setTabKeyNavigation(True)
        self.sample_rate_presets.setObjectName("sample_rate_presets")
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        self.SampleRateLayout.addWidget(self.sample_rate_presets, 1, 0, 1, 1)
        self.presets_label = QtWidgets.QLabel(self.centralwidget)
        self.presets_label.setObjectName("presets_label")
        self.SampleRateLayout.addWidget(self.presets_label, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sample_rate_min_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.sample_rate_min_btn_2.setObjectName("sample_rate_min_btn_2")
        self.horizontalLayout_3.addWidget(self.sample_rate_min_btn_2, 0, QtCore.Qt.AlignLeft)
        self.lessThan1Sample_2 = QtWidgets.QLabel(self.centralwidget)
        self.lessThan1Sample_2.setObjectName("lessThan1Sample_2")
        self.horizontalLayout_3.addWidget(self.lessThan1Sample_2)
        self.sample_rate_input_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.sample_rate_input_2.setText("")
        self.sample_rate_input_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sample_rate_input_2.setObjectName("sample_rate_input_2")
        self.horizontalLayout_3.addWidget(self.sample_rate_input_2, 0, QtCore.Qt.AlignHCenter)
        self.lessThan2Sample_2 = QtWidgets.QLabel(self.centralwidget)
        self.lessThan2Sample_2.setObjectName("lessThan2Sample_2")
        self.horizontalLayout_3.addWidget(self.lessThan2Sample_2)
        self.sample_rate_max_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.sample_rate_max_btn_2.setObjectName("sample_rate_max_btn_2")
        self.horizontalLayout_3.addWidget(self.sample_rate_max_btn_2, 0, QtCore.Qt.AlignRight)
        self.SampleRateLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.ConfigLayout.addLayout(self.SampleRateLayout, 1, 0, 1, 1)
        self.FilterLayout = QtWidgets.QGridLayout()
        self.FilterLayout.setObjectName("FilterLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(100, 50))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.filter_list = QtWidgets.QListWidget(self.centralwidget)
        self.filter_list.setMaximumSize(QtCore.QSize(200, 230))
        self.filter_list.setObjectName("filter_list")
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        self.verticalLayout_3.addWidget(self.filter_list, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.FilterLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.CornerLayout = QtWidgets.QVBoxLayout()
        self.CornerLayout.setObjectName("CornerLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(100, 50))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minCornerBox = QtWidgets.QLineEdit(self.centralwidget)
        self.minCornerBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.minCornerBox.setAlignment(QtCore.Qt.AlignCenter)
        self.minCornerBox.setReadOnly(True)
        self.minCornerBox.setObjectName("minCornerBox")
        self.horizontalLayout_4.addWidget(self.minCornerBox, 0, QtCore.Qt.AlignHCenter)
        self.lessThan1 = QtWidgets.QLabel(self.centralwidget)
        self.lessThan1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lessThan1.setObjectName("lessThan1")
        self.horizontalLayout_4.addWidget(self.lessThan1, 0, QtCore.Qt.AlignHCenter)
        self.corner_input = QtWidgets.QLineEdit(self.centralwidget)
        self.corner_input.setMaximumSize(QtCore.QSize(180, 16777215))
        self.corner_input.setAlignment(QtCore.Qt.AlignCenter)
        self.corner_input.setObjectName("corner_input")
        self.horizontalLayout_4.addWidget(self.corner_input, 0, QtCore.Qt.AlignHCenter)
        self.lessThan2 = QtWidgets.QLabel(self.centralwidget)
        self.lessThan2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lessThan2.setObjectName("lessThan2")
        self.horizontalLayout_4.addWidget(self.lessThan2, 0, QtCore.Qt.AlignHCenter)
        self.maxCornerBox = QtWidgets.QLineEdit(self.centralwidget)
        self.maxCornerBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.maxCornerBox.setAlignment(QtCore.Qt.AlignCenter)
        self.maxCornerBox.setReadOnly(True)
        self.maxCornerBox.setObjectName("maxCornerBox")
        self.horizontalLayout_4.addWidget(self.maxCornerBox, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(100, 50))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.corner_presets = QtWidgets.QListWidget(self.centralwidget)
        self.corner_presets.setObjectName("corner_presets")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.corner_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.corner_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.corner_presets.addItem(item)
        self.verticalLayout_4.addWidget(self.corner_presets, 0, QtCore.Qt.AlignHCenter)
        self.CornerLayout.addLayout(self.verticalLayout_4)
        self.FilterLayout.addLayout(self.CornerLayout, 0, 1, 1, 1)
        self.ConfigLayout.addLayout(self.FilterLayout, 4, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.ConfigLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Placeholder1 = QtWidgets.QLabel(self.centralwidget)
        self.Placeholder1.setMaximumSize(QtCore.QSize(1000, 300))
        self.Placeholder1.setObjectName("Placeholder1")
        self.horizontalLayout.addWidget(self.Placeholder1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        basic_operation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(basic_operation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        basic_operation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(basic_operation)
        self.statusbar.setObjectName("statusbar")
        basic_operation.setStatusBar(self.statusbar)
        self.actionRestart = QtWidgets.QAction(basic_operation)
        self.actionRestart.setObjectName("actionRestart")
        self.actionQuit = QtWidgets.QAction(basic_operation)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPing_CyDAQ = QtWidgets.QAction(basic_operation)
        self.actionPing_CyDAQ.setObjectName("actionPing_CyDAQ")
        self.menuFile.addAction(self.actionRestart)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionPing_CyDAQ)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(basic_operation)
        self.input_list.setCurrentRow(3)
        self.sample_rate_presets.setCurrentRow(0)
        QtCore.QMetaObject.connectSlotsByName(basic_operation)

    def retranslateUi(self, basic_operation):
        _translate = QtCore.QCoreApplication.translate
        basic_operation.setWindowTitle(_translate("basic_operation", "CyDAQ"))
        self.BasicOperationLabel.setText(_translate("basic_operation", "Basic Operation"))
        __sortingEnabled = self.input_list.isSortingEnabled()
        self.input_list.setSortingEnabled(False)
        item = self.input_list.item(0)
        item.setText(_translate("basic_operation", "5 Volt"))
        item = self.input_list.item(1)
        item.setText(_translate("basic_operation", "3.3 Volt"))
        item = self.input_list.item(2)
        item.setText(_translate("basic_operation", "1.8 Volt"))
        item = self.input_list.item(3)
        item.setText(_translate("basic_operation", "Analog In"))
        item = self.input_list.item(4)
        item.setText(_translate("basic_operation", "Audio In"))
        item = self.input_list.item(5)
        item.setText(_translate("basic_operation", "Digital I2C Bus"))
        item = self.input_list.item(6)
        item.setText(_translate("basic_operation", "Digital SPI Bus"))
        item = self.input_list.item(7)
        item.setText(_translate("basic_operation", "Digital UART"))
        self.input_list.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.sample_rate_presets.isSortingEnabled()
        self.sample_rate_presets.setSortingEnabled(False)
        item = self.sample_rate_presets.item(0)
        item.setText(_translate("basic_operation", "48000"))
        item = self.sample_rate_presets.item(1)
        item.setText(_translate("basic_operation", "44100"))
        item = self.sample_rate_presets.item(2)
        item.setText(_translate("basic_operation", "22050"))
        item = self.sample_rate_presets.item(3)
        item.setText(_translate("basic_operation", "16000"))
        item = self.sample_rate_presets.item(4)
        item.setText(_translate("basic_operation", "8000"))
        item = self.sample_rate_presets.item(5)
        item.setText(_translate("basic_operation", "4000"))
        self.sample_rate_presets.setSortingEnabled(__sortingEnabled)
        self.presets_label.setText(_translate("basic_operation", "Presets"))
        self.sample_rate_min_btn_2.setText(_translate("basic_operation", "100"))
        self.lessThan1Sample_2.setText(_translate("basic_operation", "≤"))
        self.lessThan2Sample_2.setText(_translate("basic_operation", "≤"))
        self.sample_rate_max_btn_2.setText(_translate("basic_operation", "50,000"))
        self.label_2.setText(_translate("basic_operation", "FILTER"))
        __sortingEnabled = self.filter_list.isSortingEnabled()
        self.filter_list.setSortingEnabled(False)
        item = self.filter_list.item(0)
        item.setText(_translate("basic_operation", "All Pass"))
        item = self.filter_list.item(1)
        item.setText(_translate("basic_operation", "60Hz Notch"))
        item = self.filter_list.item(2)
        item.setText(_translate("basic_operation", "1st Order High Pass"))
        item = self.filter_list.item(3)
        item.setText(_translate("basic_operation", "1st Order Low Pass"))
        item = self.filter_list.item(4)
        item.setText(_translate("basic_operation", "6th Order High Pass"))
        item = self.filter_list.item(5)
        item.setText(_translate("basic_operation", "6th Order Low Pass"))
        item = self.filter_list.item(6)
        item.setText(_translate("basic_operation", "2nd Order Band Pass"))
        item = self.filter_list.item(7)
        item.setText(_translate("basic_operation", "6th Order Band Pass"))
        self.filter_list.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("basic_operation", "Mid Corner"))
        self.minCornerBox.setText(_translate("basic_operation", "100"))
        self.lessThan1.setText(_translate("basic_operation", "≤"))
        self.corner_input.setText(_translate("basic_operation", "2,000"))
        self.lessThan2.setText(_translate("basic_operation", "≤"))
        self.maxCornerBox.setText(_translate("basic_operation", "40,000"))
        self.label_4.setText(_translate("basic_operation", "Presets"))
        __sortingEnabled = self.corner_presets.isSortingEnabled()
        self.corner_presets.setSortingEnabled(False)
        item = self.corner_presets.item(0)
        item.setText(_translate("basic_operation", "100"))
        item = self.corner_presets.item(1)
        item.setText(_translate("basic_operation", "1000"))
        item = self.corner_presets.item(2)
        item.setText(_translate("basic_operation", "10000"))
        self.corner_presets.setSortingEnabled(__sortingEnabled)
        self.Placeholder1.setText(_translate("basic_operation", "Console"))
        self.label.setText(_translate("basic_operation", "Sampling Time: 00:00:00"))
        self.pushButton.setText(_translate("basic_operation", "Start/Stop"))
        self.menuFile.setTitle(_translate("basic_operation", "Fi&le"))
        self.menuHelp.setTitle(_translate("basic_operation", "Hel&p"))
        self.actionRestart.setText(_translate("basic_operation", "&Restart"))
        self.actionQuit.setText(_translate("basic_operation", "&Quit"))
        self.actionPing_CyDAQ.setText(_translate("basic_operation", "&Ping CyDAQ"))

