# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner/CornersWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_corners_widget(object):
    def setupUi(self, corners_widget):
        corners_widget.setObjectName("corners_widget")
        corners_widget.resize(611, 480)
        corners_widget.setStyleSheet("QWidget {\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 16px;\n"
"    color: #033f63;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #033f63;\n"
"    color: #d9d9d9;\n"
"    border-radius: 4px;\n"
"    padding: 8px 21px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-radius: 4px;\n"
"    border: 2px solid #033f63;\n"
"    padding: 4px 8px;\n"
"    height: 25px;\n"
"}")
        self.label = QtWidgets.QLabel(corners_widget)
        self.label.setGeometry(QtCore.QRect(80, 30, 221, 16))
        self.label.setObjectName("label")
        self.corner_presets = QtWidgets.QListWidget(corners_widget)
        self.corner_presets.setGeometry(QtCore.QRect(180, 190, 256, 192))
        self.corner_presets.setObjectName("corner_presets")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.corner_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.corner_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.corner_presets.addItem(item)
        self.label_2 = QtWidgets.QLabel(corners_widget)
        self.label_2.setGeometry(QtCore.QRect(180, 170, 221, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(corners_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 70, 331, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.corner_min_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.corner_min_btn.setObjectName("corner_min_btn")
        self.horizontalLayout.addWidget(self.corner_min_btn)
        self.lessThan1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lessThan1.setObjectName("lessThan1")
        self.horizontalLayout.addWidget(self.lessThan1)
        self.corner_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.corner_input.setAlignment(QtCore.Qt.AlignCenter)
        self.corner_input.setObjectName("corner_input")
        self.horizontalLayout.addWidget(self.corner_input)
        self.lessThan2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lessThan2.setObjectName("lessThan2")
        self.horizontalLayout.addWidget(self.lessThan2)
        self.corner_max_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.corner_max_btn.setObjectName("corner_max_btn")
        self.horizontalLayout.addWidget(self.corner_max_btn)

        self.retranslateUi(corners_widget)
        self.corner_presets.setCurrentRow(0)
        QtCore.QMetaObject.connectSlotsByName(corners_widget)

    def retranslateUi(self, corners_widget):
        _translate = QtCore.QCoreApplication.translate
        corners_widget.setWindowTitle(_translate("corners_widget", "Form"))
        self.label.setText(_translate("corners_widget", "Mid Corner"))
        __sortingEnabled = self.corner_presets.isSortingEnabled()
        self.corner_presets.setSortingEnabled(False)
        item = self.corner_presets.item(0)
        item.setText(_translate("corners_widget", "100"))
        item = self.corner_presets.item(1)
        item.setText(_translate("corners_widget", "1000"))
        item = self.corner_presets.item(2)
        item.setText(_translate("corners_widget", "10000"))
        self.corner_presets.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("corners_widget", "Presets"))
        self.corner_min_btn.setText(_translate("corners_widget", "100"))
        self.lessThan1.setText(_translate("corners_widget", "≤"))
        self.corner_input.setText(_translate("corners_widget", "100"))
        self.lessThan2.setText(_translate("corners_widget", "≤"))
        self.corner_max_btn.setText(_translate("corners_widget", "40,000"))
