# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner/FilterWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter_widget(object):
    def setupUi(self, filter_widget):
        filter_widget.setObjectName("filter_widget")
        filter_widget.resize(622, 452)
        self.filterLabel = QtWidgets.QLabel(filter_widget)
        self.filterLabel.setGeometry(QtCore.QRect(50, 40, 181, 16))
        self.filterLabel.setObjectName("filterLabel")
        self.filterList = QtWidgets.QListWidget(filter_widget)
        self.filterList.setGeometry(QtCore.QRect(190, 110, 131, 151))
        self.filterList.setObjectName("filterList")
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filterList.addItem(item)

        self.retranslateUi(filter_widget)
        QtCore.QMetaObject.connectSlotsByName(filter_widget)

    def retranslateUi(self, filter_widget):
        _translate = QtCore.QCoreApplication.translate
        filter_widget.setWindowTitle(_translate("filter_widget", "Form"))
        self.filterLabel.setText(_translate("filter_widget", "Analog Filters"))
        __sortingEnabled = self.filterList.isSortingEnabled()
        self.filterList.setSortingEnabled(False)
        item = self.filterList.item(0)
        item.setText(_translate("filter_widget", "All Pass"))
        item = self.filterList.item(1)
        item.setText(_translate("filter_widget", "60Hz Notch"))
        item = self.filterList.item(2)
        item.setText(_translate("filter_widget", "1st Order High Pass"))
        item = self.filterList.item(3)
        item.setText(_translate("filter_widget", "1st Order Low Pass"))
        item = self.filterList.item(4)
        item.setText(_translate("filter_widget", "6th Order High Pass"))
        item = self.filterList.item(5)
        item.setText(_translate("filter_widget", "6th Order Low Pass"))
        item = self.filterList.item(6)
        item.setText(_translate("filter_widget", "2nd Order Band Pass"))
        item = self.filterList.item(7)
        item.setText(_translate("filter_widget", "6th Order Band Pass"))
        self.filterList.setSortingEnabled(__sortingEnabled)
