# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner/FilterWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter_widget(object):
    def setupUi(self, filter_widget):
        filter_widget.setObjectName("filter_widget")
        filter_widget.resize(622, 452)
        filter_widget.setStyleSheet("QWidget {\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 16px;\n"
"    color: #033f63;\n"
"}\n"
"")
        self.filter_list = QtWidgets.QListWidget(filter_widget)
        self.filter_list.setGeometry(QtCore.QRect(190, 110, 181, 221))
        self.filter_list.setObjectName("filter_list")
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.filter_list.addItem(item)

        self.retranslateUi(filter_widget)
        self.filter_list.setCurrentRow(0)
        QtCore.QMetaObject.connectSlotsByName(filter_widget)

    def retranslateUi(self, filter_widget):
        _translate = QtCore.QCoreApplication.translate
        filter_widget.setWindowTitle(_translate("filter_widget", "Form"))
        __sortingEnabled = self.filter_list.isSortingEnabled()
        self.filter_list.setSortingEnabled(False)
        item = self.filter_list.item(0)
        item.setText(_translate("filter_widget", "All Pass"))
        item = self.filter_list.item(1)
        item.setText(_translate("filter_widget", "60Hz Notch"))
        item = self.filter_list.item(2)
        item.setText(_translate("filter_widget", "1st Order High Pass"))
        item = self.filter_list.item(3)
        item.setText(_translate("filter_widget", "1st Order Low Pass"))
        item = self.filter_list.item(4)
        item.setText(_translate("filter_widget", "6th Order High Pass"))
        item = self.filter_list.item(5)
        item.setText(_translate("filter_widget", "6th Order Low Pass"))
        item = self.filter_list.item(6)
        item.setText(_translate("filter_widget", "2nd Order Band Pass"))
        item = self.filter_list.item(7)
        item.setText(_translate("filter_widget", "6th Order Band Pass"))
        self.filter_list.setSortingEnabled(__sortingEnabled)
