# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner/LiveStream.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_live_stream(object):
    def setupUi(self, live_stream):
        live_stream.setObjectName("live_stream")
        live_stream.setEnabled(True)
        live_stream.resize(700, 800)
        live_stream.setMinimumSize(QtCore.QSize(428, 625))
        live_stream.setMaximumSize(QtCore.QSize(700, 800))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setUnderline(False)
        live_stream.setFont(font)
        live_stream.setStyleSheet("background-color: #d9d9d9;")
        self.centralwidget = QtWidgets.QWidget(live_stream)
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 900))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 16px;\n"
"    color: #033f63;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #033f63;\n"
"    color: #d9d9d9;\n"
"    border-radius: 4px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"#sampling_rate_label, #input_label, #filter_label, #mid_corner_label, #low_corner_label, #high_corner_label {\n"
"    font-size: 20px;\n"
"    text-align: center;\n"
"    color: #98012e;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_btn = QtWidgets.QPushButton(self.centralwidget)
        self.home_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/assets/home_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon)
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout.addWidget(self.home_btn)
        self.live_graph = PlotWidget(self.centralwidget)
        self.live_graph.setObjectName("live_graph")
        self.verticalLayout.addWidget(self.live_graph)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.infile_line = QtWidgets.QLineEdit(self.centralwidget)
        self.infile_line.setObjectName("infile_line")
        self.horizontalLayout_2.addWidget(self.infile_line)
        self.outfile_line = QtWidgets.QLineEdit(self.centralwidget)
        self.outfile_line.setObjectName("outfile_line")
        self.horizontalLayout_2.addWidget(self.outfile_line)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        live_stream.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(live_stream)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        live_stream.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(live_stream)
        self.statusbar.setObjectName("statusbar")
        live_stream.setStatusBar(self.statusbar)
        self.actionRestart = QtWidgets.QAction(live_stream)
        self.actionRestart.setObjectName("actionRestart")
        self.actionQuit = QtWidgets.QAction(live_stream)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPing_CyDAQ = QtWidgets.QAction(live_stream)
        self.actionPing_CyDAQ.setObjectName("actionPing_CyDAQ")
        self.menuFile.addAction(self.actionRestart)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionPing_CyDAQ)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(live_stream)
        QtCore.QMetaObject.connectSlotsByName(live_stream)

    def retranslateUi(self, live_stream):
        _translate = QtCore.QCoreApplication.translate
        live_stream.setWindowTitle(_translate("live_stream", "CyDAQ"))
        self.start_btn.setText(_translate("live_stream", "Start"))
        self.stop_btn.setText(_translate("live_stream", "Stop"))
        self.menuFile.setTitle(_translate("live_stream", "Fi&le"))
        self.menuHelp.setTitle(_translate("live_stream", "Hel&p"))
        self.actionRestart.setText(_translate("live_stream", "&Restart"))
        self.actionQuit.setText(_translate("live_stream", "&Quit"))
        self.actionPing_CyDAQ.setText(_translate("live_stream", "&Ping CyDAQ"))
from pyqtgraph import PlotWidget
import basic_operation_rc
