# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner/SamplingRateWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sampling_rate_widget(object):
    def setupUi(self, sampling_rate_widget):
        sampling_rate_widget.setObjectName("sampling_rate_widget")
        sampling_rate_widget.resize(619, 600)
        self.sampleRateLabel = QtWidgets.QLabel(sampling_rate_widget)
        self.sampleRateLabel.setGeometry(QtCore.QRect(20, 30, 261, 21))
        self.sampleRateLabel.setObjectName("sampleRateLabel")
        self.sampleRateFrame = QtWidgets.QFrame(sampling_rate_widget)
        self.sampleRateFrame.setGeometry(QtCore.QRect(10, 20, 371, 291))
        self.sampleRateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sampleRateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sampleRateFrame.setObjectName("sampleRateFrame")
        self.lessThan1Sample = QtWidgets.QLabel(self.sampleRateFrame)
        self.lessThan1Sample.setGeometry(QtCore.QRect(120, 40, 16, 16))
        self.lessThan1Sample.setObjectName("lessThan1Sample")
        self.lessThan2Sample = QtWidgets.QLabel(self.sampleRateFrame)
        self.lessThan2Sample.setGeometry(QtCore.QRect(220, 40, 16, 16))
        self.lessThan2Sample.setObjectName("lessThan2Sample")
        self.min_sample_rate_box = QtWidgets.QLineEdit(self.sampleRateFrame)
        self.min_sample_rate_box.setGeometry(QtCore.QRect(60, 40, 41, 20))
        self.min_sample_rate_box.setAlignment(QtCore.Qt.AlignCenter)
        self.min_sample_rate_box.setReadOnly(True)
        self.min_sample_rate_box.setObjectName("min_sample_rate_box")
        self.input_sample_rate_box = QtWidgets.QLineEdit(self.sampleRateFrame)
        self.input_sample_rate_box.setGeometry(QtCore.QRect(150, 40, 51, 20))
        self.input_sample_rate_box.setAlignment(QtCore.Qt.AlignCenter)
        self.input_sample_rate_box.setObjectName("input_sample_rate_box")
        self.max_sample_rate_box = QtWidgets.QLineEdit(self.sampleRateFrame)
        self.max_sample_rate_box.setGeometry(QtCore.QRect(250, 40, 51, 20))
        self.max_sample_rate_box.setAlignment(QtCore.Qt.AlignCenter)
        self.max_sample_rate_box.setReadOnly(True)
        self.max_sample_rate_box.setObjectName("max_sample_rate_box")
        self.label_2 = QtWidgets.QLabel(self.sampleRateFrame)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 221, 16))
        self.label_2.setObjectName("label_2")
        self.sample_rate_presets = QtWidgets.QListWidget(self.sampleRateFrame)
        self.sample_rate_presets.setGeometry(QtCore.QRect(50, 90, 256, 192))
        self.sample_rate_presets.setObjectName("sample_rate_presets")
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.sample_rate_presets.addItem(item)

        self.retranslateUi(sampling_rate_widget)
        QtCore.QMetaObject.connectSlotsByName(sampling_rate_widget)

    def retranslateUi(self, sampling_rate_widget):
        _translate = QtCore.QCoreApplication.translate
        sampling_rate_widget.setWindowTitle(_translate("sampling_rate_widget", "Form"))
        self.sampleRateLabel.setText(_translate("sampling_rate_widget", "Sample Rate"))
        self.lessThan1Sample.setText(_translate("sampling_rate_widget", "≤"))
        self.lessThan2Sample.setText(_translate("sampling_rate_widget", "≤"))
        self.min_sample_rate_box.setText(_translate("sampling_rate_widget", "100"))
        self.input_sample_rate_box.setText(_translate("sampling_rate_widget", "48,000"))
        self.max_sample_rate_box.setText(_translate("sampling_rate_widget", "50,000"))
        self.label_2.setText(_translate("sampling_rate_widget", "Presets"))
        __sortingEnabled = self.sample_rate_presets.isSortingEnabled()
        self.sample_rate_presets.setSortingEnabled(False)
        item = self.sample_rate_presets.item(0)
        item.setText(_translate("sampling_rate_widget", "48000"))
        item = self.sample_rate_presets.item(1)
        item.setText(_translate("sampling_rate_widget", "44100"))
        item = self.sample_rate_presets.item(2)
        item.setText(_translate("sampling_rate_widget", "22050"))
        item = self.sample_rate_presets.item(3)
        item.setText(_translate("sampling_rate_widget", "16000"))
        item = self.sample_rate_presets.item(4)
        item.setText(_translate("sampling_rate_widget", "8000"))
        item = self.sample_rate_presets.item(5)
        item.setText(_translate("sampling_rate_widget", "4000"))
        self.sample_rate_presets.setSortingEnabled(__sortingEnabled)
