#!/bin/sh

# ==========================  Configfs for USB serial and USB ethernet ==========================  
# Ensures configfs is enabled
mount -t configfs none /sys/kernel/config 

cd /sys/kernel/config/usb_gadget/
mkdir g && cd g

echo 0x1d6b > idVendor  # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB    # USB 2.0
ehco "64" > bMaxPacketSize0

mkdir -p strings/0x409
echo "xxxxxxxxxxxx" > strings/0x409/serialnumber
echo "ISU"        > strings/0x409/manufacturer
echo "CyDAQ"   > strings/0x409/product

mkdir -p functions/acm.usb0    # serial (g_serial)

mkdir -p functions/rndis.usb0  # network (g_ether)
echo "15" > functions/rndis.usb0/qmult

mkdir -p configs/c.1
echo 250 > configs/c.1/MaxPower
echo 0xE0 > configs/c.1/bmAttributes

ln -s functions/rndis.usb0 configs/c.1/
ln -s functions/acm.usb0   configs/c.1/

# Start the drivers
ls /sys/class/udc/ > UDC

# Enable the network interface
ifconfig usb0 169.254.7.2 up
# ========================================================================================================

# Add any new startup commands below

